src/Entity/Command.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandRepository")
 */
class Command
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commands")
     */
    private $User;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Cart", inversedBy="command", cascade={"persist", "remove"})
     */
    private $Cart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartLine", mappedBy="command")
     */
    private $CartLine;

    public function __construct()
    {
        $this->CartLine = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->Cart;
    }

    public function setCart(?Cart $Cart): self
    {
        $this->Cart = $Cart;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection|CartLine[]
     */
    public function getCartLine(): Collection
    {
        return $this->CartLine;
    }

    public function addCartLine(CartLine $cartLine): self
    {
        if (!$this->CartLine->contains($cartLine)) {
            $this->CartLine[] = $cartLine;
            $cartLine->setCommand($this);
        }

        return $this;
    }

    public function removeCartLine(CartLine $cartLine): self
    {
        if ($this->CartLine->contains($cartLine)) {
            $this->CartLine->removeElement($cartLine);
            // set the owning side to null (unless already changed)
            if ($cartLine->getCommand() === $this) {
                $cartLine->setCommand(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Welcome!{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="{{ asset('style/style.css') }}" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two|Vast+Shadow" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Wallpoet" rel="stylesheet">
  {% block stylesheets %}{% endblock %}
  <style>
    label {
      color: white;
    }

    .icon {
      font-size: 30px;
      color: white;
      margin: 20px;
    }

    #footer {
      position:fixed;
      left: 0;
      bottom: 0;
      width: 100%;
    }
     .row {
       margin-bottom: 100px;
     }
  </style>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ path('welcome_page')}}">Vélo'Commmerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ path('home')}}">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ path('articles')}}">Articles</a>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Category
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ path('city_bike')}}">City Bike</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ path('race_bike')}}">Race Bike</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ path('mountain_bike')}}">Mountain Bike</a>
            </div>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0 mr-5" {% if is_granted ('ROLE_ADMIN') %}
          action="{{ path('admin_search')}}" {% else %} action="{{ path('user_search')}}" {% endif %}>
          <input class="form-control mr-sm-2" type="search" aria-label="Search" name="search">
          <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>

        {% if app.user is not null %}
        {% if app.user.cart is not null %}
        <a class="btn btn-primary" href="{{path('my_cart')}}">&#128722; {{app.user.cart.getCount()}}</a>
        {% endif %}
        {% else %}
        <a class="btn btn-primary" href="{{path('my_cart')}}">&#128722; 0</a>
        {% endif %}

        {% if app.user %}
        <a href="{{ path('logout')}}" class="btn btn-danger">Logout</a>
        {% else %}

        <a href="{{path('login')}}" class="btn btn-primary mr-2">Sign In</a>
        <a href="{{ path('register')}}" class="btn btn-secondary">Sign Up</a>
        {% endif %}
    </nav>
  </header>
  <section class="core">


    {% block body %}{% endblock %}
    
    {% block footer %}
    <div class="card-footer" id="footer"
      style="text-align: center; position: relative!important; color:white; background: linear-gradient(to right, rgb(8, 7, 6), rgb(117, 14, 3));">
      Vélo'Commerce
      <a class="icon" href=""><i class="fab fa-facebook"></i></a>
      <a class="icon" href=""><i class="fab fa-instagram"></i></a>
      <a class="icon" href=""><i class="fab fa-twitter"></i></a>
      <a class="icon" href=""><i class="fas fa-envelope"></i></a>
    </div>
    {% endblock footer %}
    {% block javascripts %}{% endblock %}

  </section>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>