src/Entity/Command.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandRepository")
 */
class Command
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commands")
     */
    private $User;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Cart", inversedBy="command", cascade={"persist", "remove"})
     */
    private $Cart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartLine", mappedBy="command")
     */
    private $CartLine;

    public function __construct()
    {
        $this->CartLine = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->Cart;
    }

    public function setCart(?Cart $Cart): self
    {
        $this->Cart = $Cart;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection|CartLine[]
     */
    public function getCartLine(): Collection
    {
        return $this->CartLine;
    }

    public function addCartLine(CartLine $cartLine): self
    {
        if (!$this->CartLine->contains($cartLine)) {
            $this->CartLine[] = $cartLine;
            $cartLine->setCommand($this);
        }

        return $this;
    }

    public function removeCartLine(CartLine $cartLine): self
    {
        if ($this->CartLine->contains($cartLine)) {
            $this->CartLine->removeElement($cartLine);
            // set the owning side to null (unless already changed)
            if ($cartLine->getCommand() === $this) {
                $cartLine->setCommand(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Cart", inversedBy="user", cascade={"persist", "remove"})
     */
    private $cart;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user")
     */
    private $comment;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Command", mappedBy="User")
     */
    private $commands;

    public function __construct()
    {
        $this->comment = new ArrayCollection();
        $this->commands = new ArrayCollection();
    }

    public function getId(): ? int
    {
        return $this->id;
    }

    public function getName(): ? string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ? string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ? string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ? string
    {
        return $this->role;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getRoles()
    {
        return [$this->role];
    }

    public function getSalt()
    { }

    public function eraseCredentials()
    { }

    public function __toString()
    {
        return $this->email;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getCart(): ? Cart
    {
        return $this->cart;
    }

    public function setCart(? Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->contains($comment)) {
            $this->comment->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Command[]
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setUser($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->contains($command)) {
            $this->commands->removeElement($command);
            // set the owning side to null (unless already changed)
            if ($command->getUser() === $this) {
                $command->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('name')
            ->add('email')
            ->add('password')
            // ->add('role')
            // ->add('cart')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Entity\Article;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Entity\User;
use App\Repository\ArticleRepository;
use App\Form\CommentType;
use App\Entity\Comment;



class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }



    /**
     * @Route("/profile/show-articles", name="profile_show_articles")
     */
    public function profile(ArticleRepository $repo)
    {

        $article = $repo->findAll();
        // $comments = $article->getComments();
        // dump($comments);die;

        return $this->render('article/index.html.twig', [
            'articleData' => $article
        ]);
    }

    /**
     * @Route ("/profile/one-article/{id}", name="profile_show_one_article")
     */
    public function oneArticle(Article $article, ObjectManager $objectManager, Request $request)
    {

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $comment->setDate(new \DateTime);

            $comment->setUser($this->getUser());
            $comment->setArticle($article);


            $objectManager->persist($comment);

            $objectManager->flush();
            // dump($comment);

        }

            // return $this->redirectToRoute("profile_show-articles");
            return $this->render("user/one-article.html.twig", [
                "articleList" => $article,
                'form'=> $form->createView()
            ]);
        }

        /**
     * @Route("/login", name="login")
     */
    
    public function login(AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        //$lastUsername = $authenticationUtils->getLastUsername();

        
        return $this->render('user/login.html.twig', [
            'error' => $error,
            //'userName' => $lastUsername
        ]);
        return $this->redirectToRoute('profile_show_articles');
    }
    /**
     * @Route("/profile/update_user", name="update_user")
     */
    public function updateUser(Request $request, UserPasswordEncoderInterface $encoder)
    {

        $user = $this->getUser();

        if ($this->getUser() !== $user) {
            return new Response("You dont have permisson to change this credentials.", 401);
        }
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $pass = $encoder->encodePassword($user, $user->getPassword());

            $user->setPassword($pass);

            $userData = $this->getDoctrine()->getManager();
            $userData->flush();

            return $this->redirectToRoute('login');
        }

        return $this->render("user/update-user.html.twig", [
            'form' => $form->createView()
        ]);
    }

    /** 
     * @Route("/search-user", name="user_search")
     */
    public function searchArticle(Request $request, ArticleRepository $repo)
    {
        dump($request->get('search'));
        $results = $repo->findByType($request->get('search'));

        

        return $this->render('user/search-article.html.twig', [
            'resultList' => $results
        ]);
        return $this->redirectToReferer();
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link href="{{ asset('style/adminIndex.css') }}" rel="stylesheet" />
{% endblock stylesheets %}

{% block body %}
<style>
    #buttons {
        margin-top: 40px;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6" id="buttons">
            <h1 style="color: white">Welcome, {{ app.user.name }}</h1>

            <div class="container" align="center">
                <a href="{{path('update_user')}}" class="btn btn-primary">Update LogIn Credentials</a>

                <a href="" class="btn btn-primary">Your Wishlist</a>
            </div>
        </div>
        <div class="col-sm-6" id="buttons">
            <img class="card-img-top"
                src="http://pluspng.com/img-png/biking-uphill-png-pin-bike-clipart-mountain-biking-9-900.gif"
                alt="Card image cap">
        </div>
    </div>
</div>
{% endblock body %}

templates/user/login.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
<link href="{{ asset('style/login.css') }}" rel="stylesheet" />
{% endblock stylesheets %}

{% block body %}
<style>
    label{
        color: black;
    }
</style>

<style>
    label {
        color: black;
        font-weight: bold;
    }
</style>

<div class="container" id="logincontainer">
    <div class="card" id="cardradius">
        <div class="card-header">
            <h1 class="text-center">Login</h1>
        </div>
        <div class="card-body">
            {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}
            <form action="{{ path('login') }}" method="POST">
                <label for="email">Email</label>
                <input type="email" name="_username" id="email" class="form-control">

                <label for="password">Password :</label>
                <input type="password" name="_password" id="password" class="form-control">
                <button class="btn btn-secondary mt-2">Login</button>
            </form>
        </div>
    </div>
</div>



{% endblock body %}

templates/user/one-article.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <ul>
                    {% if articleList is not null %}

                    <h5 class="card-title">Bike Type: {{articleList.type}}</h5>

                    <h6 class="card-subtitle mb-2 text-muted">Bike Model: {{articleList.model}}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Price: {{articleList.price}}$</h6>

                    {% else %}

                    <p>There's no article with this ID...</p>

                    {% endif %}

                    <img style="height:300px;" class="card-img-top" src="{{asset(articleList.imageURL)}}"
                        alt="Card image cap">
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>

                    {% if is_granted ('ROLE_USER') %}
                    <form action="{{path('add_to_cart',{article:articleList.id})}}" method="POST">

                        <input name="quantity" min="0" type="number">

                        <button>Add to basket</button>
                    </form>
                    {% endif %}
            </div>
        </div>
        </ul>
    </div>
</div>
<h3 class="col-8 row justify-content-center" style="color:white;padding-right: 202px;margin-bottom: 30px;margin-top: 30px">Comments :</h3>
<div class="row justify-content-center">
    <div class="col-8">
        {% if app.user %}
        {{form_start(form)}}
        {{form_widget(form)}}
        <button type="submit" class="btn btn-secondary">Post Comment</button>
        {{form_end(form)}}
        {% endif %}
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <h3 style="color:white">Comments :</h3>
        {% for comment in articleList.comments %}

        <div class="comment-container d-inline-block pl-3 align-top col-lg-12">
            <div style="width: 100%; color:white">
                <div class="col-lg-12">
                    <h5 class="card-title col-lg-12">{{ comment.user.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ comment.date|date('d/m/Y')}}</h6>
                    <p class="card-text col-lg-12">{{comment.content}}</p>
                </div>
            </div>
        </div>
        <hr style="border: 1px solid">
        {% endfor %}
    </div>
</div>

{% endblock body %}

templates/user/search-article.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container-fluid">
    {% if resultList is empty and not null %}

    <h1 class="heading text-white text-center mt-5" id="notfound">404 NOT FOUND</h1>
    
    <h2 class="text-white">This article doesn't exist.</h2>
    <a href="{{ path('articles')}}" class="btn btn-primary">Back</a>

    
        {% else %}
        <div class="row">
        {% for result in resultList %}
        <div class="col-md-3">
            <div class="card mt-4">
                <div class="card-body">
                    <img class="card-img-top" src="{{result.imageURL}}" alt="Card image cap">
                    <h5 class="card-title">{{result.type}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{result.price}}</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
                        content.</p>
                    <h6 class="card-subtitle mb-2 text-muted">{{result.model}}</h6>
                    <a href="{{path('one_article', {id:result.id})}}" class="card-link">More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
       
    
    {% endif %}
    
    
</div>


{% endblock body %}

templates/user/update-user.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-6">
        <h2 style="text-align:center; margin-top: 20px; color:white;">Update your login details</h2>
        {{form_start(form)}}
        {{form_start(form.email)}}
        {{form_start(form.password)}}
        {{form_widget(form)}}
        <button class="btn btn-primary" id="btn">Update Details</button>
        <!-- <p>You have successfully created a new article.</p> -->
        {{form_end(form)}}
    </div>
</div>
{% endblock body %}